import random

# Function to generate a random map
def generate_map(width, height):
    return [[' ' for _ in range(width)] for _ in range(height)]

# Function to check if a room can be placed at the given position
def can_place_room(map, top_left_x, top_left_y, room_width, room_height):
    for i in range(-1, room_height + 1):
        for j in range(-1, room_width + 1):
            if map[top_left_y + i][top_left_x + j] == '#':
                return False
    return True

# Function to add random rooms to the map
def add_random_rooms(map):
    height = len(map)
    width = len(map[0])
    total_tiles = width * height
    filled_tiles = 0
    max_attempts = 1000  # Maximum number of attempts to place a room
    attempts = 0 
    oblong_rooms = 0
    square_rooms = 0
    
    while filled_tiles < total_tiles // 2 and attempts < max_attempts:
        if square_rooms < 3:
            room_size = random.randint(4, min(width, height) // 2)  # Ensure room size is at least 4
            room_width = room_size
            room_height = room_size
            square_rooms += 1
        else:
            room_width = random.randint(2, min(width, height) // 2)  # Ensure room width is at least 2
            room_height = random.randint(2, min(width, height) // 2)  # Ensure room height is at least 2
        
        print(str(room_width) + ": Room Width")
        print(str(room_height) + ": Room Height")
        
        # Check if the room is oblong
        is_oblong = room_height / room_width >= 2 or room_width / room_height >= 2
        
        # Skip this room if it's oblong and we already have 2 oblong rooms
        if is_oblong and oblong_rooms >= 2:
            continue
        
        # If the room is oblong and we haven't reached the limit, increment the counter
        if is_oblong:
            oblong_rooms += 1
        
        top_left_x = random.randint(1, width - room_width - 1)
        top_left_y = random.randint(1, height - room_height - 1)
        
        if can_place_room(map, top_left_x, top_left_y, room_width, room_height):
            for i in range(room_height):
                for j in range(room_width):
                    if map[top_left_y + i][top_left_x + j] == ' ':
                        map[top_left_y + i][top_left_x + j] = '#'
                        filled_tiles += 1
        attempts += 1

# Main function to generate and print the map
def main():
    width = 80
    height = 25
    
    map = generate_map(width, height)
    add_random_rooms(map)
    
    for row in map:
        print(''.join(row))

if __name__ == "__main__":
    main()

# Generated by Copilot