import subprocess
import requests
import os
from getpass import getpass

# Step 1: Check if Git is installed
def check_git_installed():
    try:
        subprocess.run(["git", "--version"], check=True)
    except subprocess.CalledProcessError:
        print("Git is not installed. Please install Git and try again.")
        exit(1)

# Step 2: Initialize a Git repository
def initialize_git_repo():
    subprocess.run(["git", "init"], check=True)

# Step 3: Create a new repository on GitHub using login credentials
def create_github_repo(repo_name, username, password):
    url = "https://api.github.com/user/repos"
    headers = {
        "Accept": "application/vnd.github.v3+json"
    }
    data = {
        "name": repo_name,
        "private": False  # Change to True if you want a private repository
    }
    response = requests.post(url, headers=headers, json=data, auth=(username, password))
    if response.status_code == 201:
        print(f"Successfully created repository {repo_name} on GitHub.")
        return response.json()["clone_url"]
    else:
        print(f"Failed to create repository {repo_name} on GitHub.")
        print(f"Response: {response.json()}")
        exit(1)

# Step 4: Add all files to the Git repository and push to GitHub
def add_and_push_files(repo_url):
    subprocess.run(["git", "add", "."], check=True)
    subprocess.run(["git", "commit", "-m", "Initial commit"], check=True)
    subprocess.run(["git", "remote", "add", "origin", repo_url], check=True)
    subprocess.run(["git", "push", "-u", "origin", "master"], check=True)

# Main function to execute the steps
def main():
    repo_name = input("Enter the name of the repository: ")
    username = input("Enter your GitHub username: ")
    password = getpass("Enter your GitHub password: ")

    check_git_installed()
    initialize_git_repo()
    repo_url = create_github_repo(repo_name, username, password)
    add_and_push_files(repo_url)

if __name__ == "__main__":
    main()

# Generated by Copilot