import requests

# URL of the local server
url = 'http://127.0.0.1:5000/generate-images'

# Data to send in the POST request
data = {
    'text': 'A lady walking up to the house at 8964 S Newberry Ln., Tempe, AZ, and talking about debt collection.',
    'num_images': 5
}

# Send POST request to generate images
response = requests.post(url, json=data)

# Print the raw response content
print("Raw response content for images:", response.content)

# Print the response as JSON if possible
try:
    print("JSON response for images:", response.json())
except requests.exceptions.JSONDecodeError:
    print("Failed to decode JSON response for images")

# URL of the local server for video generation
url_video = 'http://127.0.0.1:5000/generate-video'

# Data to send in the POST request
data_video = {
    'text': 'A lady walking up to the house at 8964 S Newberry Ln., Tempe, AZ, and talking about debt collection.',
    'num_images': 24,
    'fps': 24
}

# Send POST request to generate video
response_video = requests.post(url_video, json=data_video)

# Print the raw response content
print("Raw response content for video:", response_video.content)

# Print the response as JSON if possible
try:
    print("JSON response for video:", response_video.json())
except requests.exceptions.JSONDecodeError:
    print("Failed to decode JSON response for video")

# Generated by Copilot